server:
  port: 8081

spring:
  application:
    name: cart
  security:
    oauth2:
      client:
        registration:
          cart-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: pricing
        provider:
          okta:
            issuer-uri: https://dev-640429.okta.com/oauth2/default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
okta:
  oauth2:
    issuer: https://dev-640429.okta.com/oauth2/default
    audience: api://default


